package com.example.model

import androidx.annotation.DrawableRes
import com.example.R

data class CategoryItem(
  val id: String,
  val name: String,
  val emoji: String,
  val subtitle: String,
)

data class Product(
  val id: String,
  val brand: String,
  val name: String,
  val categoryId: String,
  val categoryName: String,
  @DrawableRes val imageRes: Int,
  val priceTag: String = "Prix sur demande",
  val description: String,
  val keySpecs: List<String>,
  val isPopular: Boolean = true,
  val inStock: Boolean = true,
  val warrantyMonths: Int = 12,
)

object ShopData {
  val categories = listOf(
    CategoryItem(
      id = "cuisinieres",
      name = "Cuisinières",
      emoji = "🍳",
      subtitle = "Fours & Feux Inox",
    ),
    CategoryItem(
      id = "refrigerateurs",
      name = "Réfrigérateurs",
      emoji = "🧊",
      subtitle = "No Frost & Combi",
    ),
    CategoryItem(
      id = "petit_electro",
      name = "Petit électroménager",
      emoji = "☕",
      subtitle = "Café, Friteuses, etc.",
    ),
    CategoryItem(
      id = "robots_mixeurs",
      name = "Robots & Mixeurs",
      emoji = "🥣",
      subtitle = "Pétrins & Hachoirs",
    ),
  )

  val products = listOf(
    Product(
      id = "arcodym-cuisiniere-lf699",
      brand = "ARCODYM",
      name = "Cuisinière LF699-GGF50F Inox",
      categoryId = "cuisinieres",
      categoryName = "Cuisinières",
      imageRes = R.drawable.img_cuisiniere_arcodym,
      priceTag = "Prix sur demande",
      description = "Cuisinière tout inox professionnelle haute résistance. Dispose de 5 brûleurs puissants dont un triple couronne spécial cuisson rapide, allumage intégré automatique, grand four ventilé avec tournebroche et minuterie.",
      keySpecs = listOf(
        "Finition 100% Acier Inoxydable brossé",
        "5 brûleurs à gaz haute efficacité (1 triple couronne)",
        "Grand four à gaz ventilé avec tournebroche",
        "Allumage électronique à une main",
        "Sécurité thermocouple totale table et four",
        "Garantie 12 mois avec service après-vente assuré",
      ),
      isPopular = true,
    ),
    Product(
      id = "schallenge-robot-multifonction",
      brand = "SCHALLENGE",
      name = "Robot multifonction Schallenge",
      categoryId = "robots_mixeurs",
      categoryName = "Robots & Mixeurs",
      imageRes = R.drawable.img_robot_schallenge,
      priceTag = "Prix sur demande",
      description = "Le robot pétrin et préparateur multifonction indispensable pour vos pâtes, gâteaux, brioches et crèmes. Bol géant en acier inox de 7 litres, moteur ultra performant avec transmission métallique et bol blender en verre.",
      keySpecs = listOf(
        "Moteur haute performance 1500 Watts",
        "Bol inox grande capacité 7 Litres avec poignée",
        "6 vitesses réglables + fonction Pulse",
        "Kit pâtisserie complet : Crochet pétrisseur, Batteur plat, Fouet ballon",
        "Blender en verre trempé 1.5L inclus",
        "Garantie 12 mois ROKA ELECTRO",
      ),
      isPopular = true,
    ),
    Product(
      id = "schallenge-robot-noir",
      brand = "SCHALLENGE",
      name = "Robot multifonction Schallenge Noir",
      categoryId = "robots_mixeurs",
      categoryName = "Robots & Mixeurs",
      imageRes = R.drawable.img_robot_schallenge,
      priceTag = "Prix sur demande",
      description = "Édition Deluxe Noire mate du célèbre robot multifonction Schallenge. Finition premium anti-traces, puissance renforcée, silencieux et ultra robuste pour une utilisation quotidienne et intensive.",
      keySpecs = listOf(
        "Édition spéciale Black Matte élégante",
        "Moteur renforcé 1500 Watts ultra silencieux",
        "Bol en acier inoxydable poli 7 Litres",
        "Pieds ventouses anti-dérapants ultra stables",
        "Accessoires lavables au lave-vaisselle",
        "Garantie 12 mois SAV ROKA ELECTRO",
      ),
      isPopular = true,
    ),
    Product(
      id = "midea-refrigerateur",
      brand = "MIDEA",
      name = "Réfrigérateur",
      categoryId = "refrigerateurs",
      categoryName = "Réfrigérateurs",
      imageRes = R.drawable.img_refrigerateur_midea,
      priceTag = "Prix sur demande",
      description = "Réfrigérateur moderne double porte Total No Frost par Midea. Économie d'énergie remarquable, froid ventilé homogène Multi Air Flow sans givre, clayettes en verre trempé réglables et compartiment fraîcheur fruits & légumes.",
      keySpecs = listOf(
        "Technologie Total No Frost (zéro dégivrage)",
        "Système Multi-Air Flow circulation dynamique",
        "Finitions inox anti-traces de doigts",
        "Compresseur Inverter silencieux et économique",
        "Éclairage LED intérieur lumineux et économique",
        "Garantie 12 mois ROKA ELECTRO",
      ),
      isPopular = true,
    ),
    Product(
      id = "arcodym-hachoir-dym-c022c",
      brand = "ARCODYM",
      name = "Hachoir DYM-C022C — 350 W",
      categoryId = "petit_electro",
      categoryName = "Petit électroménager",
      imageRes = R.drawable.ic_chopper_placeholder,
      priceTag = "Prix sur demande",
      description = "Hachoir électrique polyvalent Arcodym 350 Watts. Équipé d'un bol en verre épais de 2 Litres et de 4 lames en acier inoxydable étagées pour hacher viande, oignons, noix et fines herbes en quelques secondes.",
      keySpecs = listOf(
        "Puissance 350 Watts efficace",
        "Bol en verre transparent haute résistance 2 Litres",
        "4 lames inox amovibles bi-niveaux",
        "2 vitesses de hachage selon les aliments",
        "Base antidérapante en caoutchouc silicone",
        "Garantie 12 mois",
      ),
      isPopular = true,
    ),
    Product(
      id = "raylan-cafetiere-expresso",
      brand = "RAYLAN",
      name = "Cafetière Expresso 15 Bar",
      categoryId = "petit_electro",
      categoryName = "Petit électroménager",
      imageRes = R.drawable.ic_coffee_placeholder,
      priceTag = "Prix sur demande",
      description = "Machine expresso manuelle avec pompe pression 15 bars pour un café riche en arômes et une crème dorée onctueuse. Buse vapeur inox intégrée pour préparer cappuccinos et latte macchiato comme au café.",
      keySpecs = listOf(
        "Pression de pompe italienne 15 Bars",
        "Buse vapeur orientable pour mousse de lait",
        "Filtre 1 ou 2 tasses compatible café moulu & dosettes",
        "Réservoir d'eau amovible transparent 1.25L",
        "Plateau chauffe-tasses supérieur en inox",
        "Garantie 12 mois ROKA ELECTRO",
      ),
      isPopular = false,
    ),
    Product(
      id = "brandt-airfryer-5l",
      brand = "BRANDT",
      name = "Friteuse Sans Huile Air Fryer 5.5L",
      categoryId = "petit_electro",
      categoryName = "Petit électroménager",
      imageRes = R.drawable.ic_airfryer_placeholder,
      priceTag = "Prix sur demande",
      description = "Cuisinez croustillant avec jusqu'à 85% d'huile en moins ! Grande cuve de 5.5L familiale, panneau de commande digital tactile avec 8 pré-réglages automatiques pour frites, poulet, poissons, viandes et pâtisseries.",
      keySpecs = listOf(
        "Capacité familiale 5.5 Litres (jusqu'à 6 personnes)",
        "Puissance 1700 Watts à convection rapide 360°",
        "8 programmes tactiles automatiques",
        "Thermostat réglable de 80°C à 200°C",
        "Tiroir et panier anti-adhésifs amovibles",
        "Garantie 12 mois ROKA ELECTRO",
      ),
      isPopular = false,
    ),
  )
}
